// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Produtos.Api.Data;

#nullable disable

namespace TechStore.Produtos.Api.Data.Migrations
{
    [DbContext(typeof(ProdutosDbContext))]
    partial class ProdutosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Produtos.Api.Domain.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2a10-0001-4c3e-9a51-000000000001"),
                            Categoria = "E-books",
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descricao = "Guia prático com padrões de projeto, observabilidade e segurança.",
                            Estoque = 9999,
                            Nome = "E-book: Arquitetura de Microsserviços na Azure",
                            Preco = 59.90m,
                            Sku = "EBOOK-AZ-001"
                        },
                        new
                        {
                            Id = new Guid("6f1c2a10-0002-4c3e-9a51-000000000002"),
                            Categoria = "Cursos",
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descricao = "40 horas de conteúdo em vídeo, com certificado.",
                            Estoque = 500,
                            Nome = "Curso online: APIs REST com .NET",
                            Preco = 349.00m,
                            Sku = "CURSO-NET-010"
                        },
                        new
                        {
                            Id = new Guid("6f1c2a10-0003-4c3e-9a51-000000000003"),
                            Categoria = "Licenças de software",
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descricao = "Licença individual de 12 meses, com atualizações.",
                            Estoque = 120,
                            Nome = "Licença anual: IDE Pro",
                            Preco = 899.00m,
                            Sku = "LIC-IDE-PRO-1A"
                        },
                        new
                        {
                            Id = new Guid("6f1c2a10-0004-4c3e-9a51-000000000004"),
                            Categoria = "Gift cards",
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descricao = "Crédito para uso em toda a loja, válido por 12 meses.",
                            Estoque = 1000,
                            Nome = "Gift card digital R$ 100",
                            Preco = 100.00m,
                            Sku = "GIFT-100"
                        },
                        new
                        {
                            Id = new Guid("6f1c2a10-0005-4c3e-9a51-000000000005"),
                            Categoria = "Assinaturas",
                            CriadoEm = new DateTimeOffset(new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Descricao = "Acesso a laboratórios guiados de Azure, renovação mensal.",
                            Estoque = 300,
                            Nome = "Assinatura mensal: Laboratórios Cloud",
                            Preco = 79.90m,
                            Sku = "ASSIN-CLOUD-M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
